# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2.1
jobs:
  buildDebug:
    working_directory: ~/EasyRetro
    docker:
      - image: circleci/android:api-28
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle.kts" }}-{{ checksum  "buildSrc/src/main/java/Dependencies.kt" }}-{{ checksum  "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          # Decode the base64 string
          name: Decode Google Services Json
          command: echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json
      - run:
          name: Run Lint
          command: ./gradlew lintDebug
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - run:
          name: Build
          command: ./gradlew assembleDebug
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}-{{ checksum  "buildSrc/src/main/java/Dependencies.kt" }}-{{ checksum  "gradle/wrapper/gradle-wrapper.properties" }}
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
  buildRelease:
    working_directory: ~/EasyRetro
    docker:
        - image: circleci/android:api-28
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle.kts" }}-{{ checksum  "buildSrc/src/main/java/Dependencies.kt" }}-{{ checksum  "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Decode Google Services Json
          command: echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json
      - run:
          name: Create release.keystore
          command: echo $RELEASE_KEYSTORE | base64 --decode > $CI_STORE_FILE
      - run:
          name: Run Lint
          command: ./gradlew lintRelease
      - run:
          name: Run Unit Tests
          command: ./gradlew testReleaseUnitTest
      - run:
          name: Build
          command: ./gradlew clean assembleRelease --no-daemon --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}-{{ checksum  "buildSrc/src/main/java/Dependencies.kt" }}-{{ checksum  "gradle/wrapper/gradle-wrapper.properties" }}
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
workflows:
  version: 1
  check:
    jobs:
      - buildDebug
  distribution:
    jobs:
      - buildRelease
