package com.easyretro.analytics

enum class Screen {
    WELCOME,
    SIGN_IN,
    SIGN_UP,
    VERIFY_EMAIL,
    RESET_PASSWORD,
    RETRO_LIST,
    RETRO_BOARD
}

enum class UiValue {
    GOOGLE_SIGN_IN,
    WELCOME_EMAIL_SIGN_IN,
    WELCOME_EMAIL_SIGN_UP,
    ACCOUNT_SIGN_IN,
    ACCOUNT_SIGN_UP,
    ACCOUNT_RESET_PASSWORD,
    RESET_PASSWORD_CONFIRM,
    OPEN_EMAIL_APP,
    RESEND_EMAIL_VERIFICATION,
    SIGN_OUT,
    SIGN_OUT_CONFIRMATION,
    SIGN_OUT_DISMISS,
    RETRO_CREATE,
    RETRO_ITEM,
    STATEMENT_CREATE,
    STATEMENT_REMOVE,
    STATEMENT_REMOVE_CONFIRMATION,
    STATEMENT_REMOVE_DISMISS,
    RETRO_INVITE,
    RETRO_PROTECT,
    RETRO_PROTECT_CONFIRMATION,
    RETRO_PROTECT_DISMISS,
    RETRO_UNPROTECT,
    BACK
}